"""Core components for world models."""

from .batch import (
    Batch,
    BatchProvider,
    BatchProviderV2,
    BatchRequest,
    SequenceProvider,
    TokenProvider,
    TransitionProvider,
    VideoProvider,
)
from .config import (
    DiffusionWorldModelConfig,
    DreamerV3Config,
    DynamicsType,
    JEPABaseConfig,
    LatentType,
    TDMPC2Config,
    TokenWorldModelConfig,
    VJEPA2Config,
    WorldModelConfig,
)
from .exceptions import (
    BufferError,
    CapabilityError,
    CheckpointError,
    ConfigurationError,
    ModelNotFoundError,
    ShapeMismatchError,
    StateError,
    TrainingError,
    ValidationError,
    WorldFluxError,
)
from .interfaces import (
    ActionConditioner,
    AsyncDecoder,
    AsyncDecoderAdapter,
    AsyncDynamicsModel,
    AsyncDynamicsModelAdapter,
    AsyncObservationEncoder,
    AsyncObservationEncoderAdapter,
    AsyncRolloutExecutor,
    AsyncRolloutExecutorAdapter,
    ComponentSpec,
    Decoder,
    DynamicsModel,
    ObservationEncoder,
    RolloutEngine,  # noqa: F401 — kept for backward compat, deprecated
    RolloutExecutor,
    ensure_async_decoder,
    ensure_async_dynamics_model,
    ensure_async_observation_encoder,
    ensure_async_rollout_executor,
)
from .latent_space import (
    CategoricalLatentSpace,
    GaussianLatentSpace,
    LatentSpace,
    SimNormLatentSpace,
)
from .model import WorldModel
from .output import LossOutput, ModelOutput, WorldModelOutput
from .payloads import (
    ACTION_COMPONENTS_KEY,
    PLANNER_HORIZON_KEY,
    PLANNER_SEQUENCE_KEY,
    ActionPayload,
    ActionSequence,
    ConditionPayload,
    WorldModelInput,
    first_action,  # noqa: F401 — kept for backward compat, deprecated
    is_namespaced_extra_key,  # noqa: F401 — kept for backward compat, deprecated
    normalize_planned_action,
)
from .registry import AutoConfig, AutoWorldModel, PluginManifest, WorldModelRegistry
from .spec import (
    ActionSpec,
    Capability,
    ConditionSpec,
    ModalityKind,
    ModalitySpec,
    ModelIOContract,
    ModelMaturity,
    ObservationSpec,
    PredictionSpec,
    SequenceFieldSpec,
    SequenceLayout,
    StateSpec,
    TokenSpec,
)
from .state import State
from .trajectory import Trajectory

__all__ = [
    # State and Trajectory
    "State",
    "Trajectory",
    "Batch",
    "BatchRequest",
    "BatchProvider",
    "BatchProviderV2",
    "TransitionProvider",
    "SequenceProvider",
    "TokenProvider",
    "VideoProvider",
    "ModelOutput",
    "WorldModelOutput",
    "LossOutput",
    "ActionPayload",
    "ActionSequence",
    "ConditionPayload",
    "WorldModelInput",
    "normalize_planned_action",
    "PLANNER_HORIZON_KEY",
    "PLANNER_SEQUENCE_KEY",
    "ACTION_COMPONENTS_KEY",
    "ComponentSpec",
    "ObservationEncoder",
    "AsyncObservationEncoder",
    "AsyncObservationEncoderAdapter",
    "ensure_async_observation_encoder",
    "DynamicsModel",
    "AsyncDynamicsModel",
    "AsyncDynamicsModelAdapter",
    "ensure_async_dynamics_model",
    "ActionConditioner",
    "Decoder",
    "AsyncDecoder",
    "AsyncDecoderAdapter",
    "ensure_async_decoder",
    "RolloutExecutor",
    "AsyncRolloutExecutor",
    "AsyncRolloutExecutorAdapter",
    "ensure_async_rollout_executor",
    # Specs
    "ModalityKind",
    "ModalitySpec",
    "ObservationSpec",
    "ActionSpec",
    "ConditionSpec",
    "StateSpec",
    "TokenSpec",
    "PredictionSpec",
    "SequenceFieldSpec",
    "SequenceLayout",
    "ModelIOContract",
    "Capability",
    "ModelMaturity",
    # Config
    "LatentType",
    "DynamicsType",
    "WorldModelConfig",
    "DreamerV3Config",
    "TDMPC2Config",
    "JEPABaseConfig",
    "VJEPA2Config",
    "TokenWorldModelConfig",
    "DiffusionWorldModelConfig",
    # Protocol and Registry
    "WorldModel",
    "WorldModelRegistry",
    "AutoWorldModel",
    "AutoConfig",
    "PluginManifest",
    # Latent Spaces
    "LatentSpace",
    "GaussianLatentSpace",
    "CategoricalLatentSpace",
    "SimNormLatentSpace",
    # Exceptions
    "WorldFluxError",
    "ConfigurationError",
    "ShapeMismatchError",
    "StateError",
    "ModelNotFoundError",
    "CheckpointError",
    "TrainingError",
    "BufferError",
    "ValidationError",
    "CapabilityError",
]
