"""Core components for world models."""

from .batch import (
    Batch,
    BatchProvider,
    SequenceProvider,
    TokenProvider,
    TransitionProvider,
    VideoProvider,
)
from .config import (
    DiffusionWorldModelConfig,
    DiTSkeletonConfig,
    DreamerV3Config,
    DynamicsType,
    GANSkeletonConfig,
    JEPABaseConfig,
    LatentType,
    PhysicsSkeletonConfig,
    Renderer3DSkeletonConfig,
    SSMSkeletonConfig,
    TDMPC2Config,
    TokenWorldModelConfig,
    VJEPA2Config,
    WorldModelConfig,
)
from .exceptions import (
    BufferError,
    CapabilityError,
    CheckpointError,
    ConfigurationError,
    ModelNotFoundError,
    ShapeMismatchError,
    StateError,
    TrainingError,
    ValidationError,
    WorldFluxError,
)
from .interfaces import (
    ActionConditioner,
    ComponentSpec,
    Decoder,
    DynamicsModel,
    ObservationEncoder,
    RolloutEngine,
    RolloutExecutor,
)
from .latent_space import (
    CategoricalLatentSpace,
    GaussianLatentSpace,
    LatentSpace,
    SimNormLatentSpace,
)
from .model import WorldModel
from .output import LossOutput, ModelOutput, WorldModelOutput
from .payloads import (
    ACTION_COMPONENTS_KEY,
    PLANNER_HORIZON_KEY,
    PLANNER_SEQUENCE_KEY,
    ActionPayload,
    ActionSequence,
    ConditionPayload,
    WorldModelInput,
    first_action,
    is_namespaced_extra_key,
    normalize_planned_action,
)
from .registry import AutoConfig, AutoWorldModel, WorldModelRegistry
from .spec import (
    ActionSpec,
    Capability,
    ConditionSpec,
    ModalityKind,
    ModalitySpec,
    ModelIOContract,
    ModelMaturity,
    ObservationSpec,
    PredictionSpec,
    SequenceLayout,
    StateSpec,
    TokenSpec,
)
from .state import State
from .trajectory import Trajectory

__all__ = [
    # State and Trajectory
    "State",
    "Trajectory",
    "Batch",
    "BatchProvider",
    "TransitionProvider",
    "SequenceProvider",
    "TokenProvider",
    "VideoProvider",
    "ModelOutput",
    "WorldModelOutput",
    "LossOutput",
    "ActionPayload",
    "ActionSequence",
    "ConditionPayload",
    "WorldModelInput",
    "normalize_planned_action",
    "first_action",
    "PLANNER_HORIZON_KEY",
    "PLANNER_SEQUENCE_KEY",
    "ACTION_COMPONENTS_KEY",
    "is_namespaced_extra_key",
    "ComponentSpec",
    "ObservationEncoder",
    "DynamicsModel",
    "ActionConditioner",
    "Decoder",
    "RolloutExecutor",
    "RolloutEngine",
    # Specs
    "ModalityKind",
    "ModalitySpec",
    "ObservationSpec",
    "ActionSpec",
    "ConditionSpec",
    "StateSpec",
    "TokenSpec",
    "PredictionSpec",
    "SequenceLayout",
    "ModelIOContract",
    "Capability",
    "ModelMaturity",
    # Config
    "LatentType",
    "DynamicsType",
    "WorldModelConfig",
    "DreamerV3Config",
    "TDMPC2Config",
    "JEPABaseConfig",
    "VJEPA2Config",
    "TokenWorldModelConfig",
    "DiffusionWorldModelConfig",
    "DiTSkeletonConfig",
    "SSMSkeletonConfig",
    "Renderer3DSkeletonConfig",
    "PhysicsSkeletonConfig",
    "GANSkeletonConfig",
    # Protocol and Registry
    "WorldModel",
    "WorldModelRegistry",
    "AutoWorldModel",
    "AutoConfig",
    # Latent Spaces
    "LatentSpace",
    "GaussianLatentSpace",
    "CategoricalLatentSpace",
    "SimNormLatentSpace",
    # Exceptions
    "WorldFluxError",
    "ConfigurationError",
    "ShapeMismatchError",
    "StateError",
    "ModelNotFoundError",
    "CheckpointError",
    "TrainingError",
    "BufferError",
    "ValidationError",
    "CapabilityError",
]
